### ISSUE TITLE
Multiple ofxTonicSynth instances

### ISSUE THREAD

**Issue by 1am** [TonicAudio/ofxTonic#14]
Hi

I've been trying to use a few synths simultaneously but only the last one seems to be audible depending on the order of calls of `.fillBufferOfFloats(output, bufferSize, nChannels);`.

In the following code only synth 0 will work:

```
_synths[1].fillBufferOfFloats(output, bufferSize, nChannels);
_synths[0].fillBufferOfFloats(output, bufferSize, nChannels);
```

in this one only synth 1 will be audible:

```
_synths[0].fillBufferOfFloats(output, bufferSize, nChannels);
_synths[1].fillBufferOfFloats(output, bufferSize, nChannels);
```

Otherwise they work correctly, don't have any audio dropouts or other cpu usage errors. Is it possible to use more than one ofxTonicSynth at once?

**Comment by ndonald2** [comment]
`fillBufferOfFloats` overwrites the buffer in the first argument. So if you're trying to sum the output from multiple synths, you can render the first synth into the main output buffer but you'll need to render all the others into a temporary buffer and then add it to your main output buffer.

e.g. for your situation with just 2 synths:

``` c++
// In constructor or class init
_tempBuffer = calloc(bufferSize * nChannels, sizeof(float)); // or vector, if you really want to

// In render call
_synths[0].fillBufferOfFloats(output, bufferSize, nChannels);
_synths[1].fillBufferOfFloats(_tempBuffer, bufferSize, nChannels);

// Assuming both have same number of channels
for (int i = 0; i < bufferSize * nChannels; i++) {
    output[i] += _tempBuffer[i];
}
```

**Comment by 1am** [comment]
You're right. Thank you.

For reference I've ended up implementing it the following way:

```
    for( vector<ofxTonicSynth>::iterator it = _synths.begin() ; it != _synths.end() ; it++ ){
        (it)->fillBufferOfFloats(_tmpBuffer, bufferSize, nChannels);
        for (int i = 0; i < bufferSize * nChannels; i++) {
            output[i] += _tmpBuffer[i];
        }
    }

```
