### ISSUE TITLE
Using MIDI input, only one signal is playing at a time

### ISSUE THREAD

**Issue by sabernar** [TonicAudio/ofxTonic#7]
(Apologies for the newb issue, but I'm relatively new to the world of MIDI and sound synth.)

I'm sure I'm doing something wrong, but every time I create a new signal with ofxTonic, the previous signal is stopped.  I would think that there is a way to play all of the signals (i.e., play a C chord and have them all play together), but I am at a loss.

Thanks,

**Comment by mihnor** [comment]
hi there, i'm facing a lot of issues to make PolyMIDIDemo work at Yosemite.
I copied the RtMidi.cpp and h. I removed ofxTonic.h. 

```
Undefined` symbols for architecture i386:
  "_kMIDIPropertyName", referenced from:
      EndpointName(unsigned long, bool) in RtMidi.o
      ConnectedEndpointName(unsigned long) in RtMidi.o
  "_kMIDIPropertyConnectionUniqueID", referenced from:
      ConnectedEndpointName(unsigned long) in RtMidi.o

```
